"""
QR Code Generator — Flask Web Application
"""
import os
from flask import Flask, render_template, request, jsonify, send_from_directory
from werkzeug.utils import secure_filename
from urllib.parse import quote, unquote
import base64
from qr_engine import generate_qr

app = Flask(__name__)
app.config["MAX_CONTENT_LENGTH"] = 5 * 1024 * 1024  # 5 MB max upload
app.config["UPLOAD_FOLDER"] = os.path.join(os.path.dirname(__file__), "uploads")
app.config["OUTPUT_FOLDER"] = os.path.join(os.path.dirname(__file__), "static", "generated")

ALLOWED_EXTENSIONS = {"png", "jpg", "jpeg", "gif", "svg", "webp"}

os.makedirs(app.config["UPLOAD_FOLDER"], exist_ok=True)
os.makedirs(app.config["OUTPUT_FOLDER"], exist_ok=True)


def allowed_file(filename: str) -> bool:
    return "." in filename and filename.rsplit(".", 1)[1].lower() in ALLOWED_EXTENSIONS


# --------------- Routes ---------------

@app.route("/")
def index():
    return render_template("index.html")


@app.route("/generate", methods=["POST"])
def generate():
    try:
        payload = request.get_json()
        if not payload:
            return jsonify({"error": "No data provided"}), 400

        qr_type = payload.get("qr_type", "url")
        data = payload.get("data", {})

        # iOS compatibility: wrap plain text as a URL
        if qr_type == "text" and data.get("_iosCompat"):
            text_content = data.get("text", "")
            host = request.host
            scheme = request.scheme
            # Use base64 to safely encode any text (newlines, colons, etc.)
            b64 = base64.urlsafe_b64encode(text_content.encode('utf-8')).decode('ascii')
            data = {"url": f"{scheme}://{host}/t?d={b64}"}
            qr_type = "url"

        fg_color = payload.get("fg_color", "#000000")
        bg_color = payload.get("bg_color", "#FFFFFF")
        gradient_end = payload.get("gradient_end")
        color_style = payload.get("color_style", "solid")
        module_style = payload.get("module_style", "square")
        error_correction = payload.get("error_correction", "M")
        logo_filename = payload.get("logo_filename")
        output_format = payload.get("output_format", "png")
        size = int(payload.get("size", 20))
        border = int(payload.get("border", 4))

        logo_path = None
        if logo_filename:
            logo_path = os.path.join(app.config["UPLOAD_FOLDER"], logo_filename)
            if not os.path.exists(logo_path):
                logo_path = None

        filename = generate_qr(
            qr_type=qr_type,
            data=data,
            fg_color=fg_color,
            bg_color=bg_color,
            gradient_end=gradient_end,
            color_style=color_style,
            module_style=module_style,
            error_correction=error_correction,
            logo_path=logo_path,
            output_format=output_format,
            size=size,
            border=border,
            output_dir=app.config["OUTPUT_FOLDER"],
        )

        file_url = f"/static/generated/{filename}"
        download_url = f"/download/{filename}"

        return jsonify({
            "success": True,
            "filename": filename,
            "file_url": file_url,
            "download_url": download_url,
        })

    except Exception as e:
        return jsonify({"error": str(e)}), 500


@app.route("/download/<filename>")
def download(filename):
    return send_from_directory(
        app.config["OUTPUT_FOLDER"],
        filename,
        as_attachment=True,
    )


@app.route("/t")
def show_text():
    """Display QR code text content — used for iOS compatibility."""
    b64_data = request.args.get('d', '')
    try:
        decoded = base64.urlsafe_b64decode(b64_data.encode('ascii')).decode('utf-8')
    except Exception:
        decoded = unquote(b64_data)
    
    # Escape HTML to prevent XSS
    import html
    safe_text = html.escape(decoded).replace('\n', '<br>')
    
    return f'''<!DOCTYPE html>
<html><head><title>QR Code Content</title>
<meta name="viewport" content="width=device-width,initial-scale=1">
<style>
  body{{margin:0;min-height:100vh;display:flex;align-items:center;justify-content:center;
    background:#0a0a0f;color:#e8e8f0;font-family:-apple-system,BlinkMacSystemFont,sans-serif;padding:24px;}}
  .card{{max-width:600px;width:100%;background:rgba(18,18,28,0.9);border:1px solid rgba(255,255,255,0.06);
    border-radius:16px;padding:32px;box-shadow:0 8px 32px rgba(0,0,0,0.5);}}
  .label{{font-size:0.75rem;text-transform:uppercase;letter-spacing:0.1em;color:#8888a0;margin-bottom:12px;}}
  .content{{font-size:1.1rem;line-height:1.7;word-break:break-word;}}
  .footer{{margin-top:24px;font-size:0.7rem;color:#555568;text-align:center;}}
</style>
</head><body>
<div class="card">
  <div class="label">QR Code Content</div>
  <div class="content">{safe_text}</div>
  <div class="footer">Generated by QR Forge</div>
</div>
</body></html>'''


@app.route("/view/<filename>")
def view_qr(filename):
    """Serve a standalone page with just the QR code — ideal for phone scanning."""
    return f'''<!DOCTYPE html>
<html><head><title>Scan QR Code</title>
<meta name="viewport" content="width=device-width,initial-scale=1">
<style>body{{margin:0;min-height:100vh;display:flex;align-items:center;justify-content:center;background:#fff;}}
img{{max-width:90vmin;max-height:90vmin;image-rendering:pixelated;}}</style>
</head><body><img src="/static/generated/{filename}" alt="QR Code"></body></html>'''


@app.route("/upload-logo", methods=["POST"])
def upload_logo():
    if "logo" not in request.files:
        return jsonify({"error": "No file provided"}), 400

    file = request.files["logo"]
    if file.filename == "":
        return jsonify({"error": "No file selected"}), 400

    if not allowed_file(file.filename):
        return jsonify({"error": "File type not allowed"}), 400

    filename = secure_filename(file.filename)
    # Add unique prefix to avoid collisions
    import uuid
    unique_name = f"{uuid.uuid4().hex[:8]}_{filename}"
    filepath = os.path.join(app.config["UPLOAD_FOLDER"], unique_name)
    file.save(filepath)

    return jsonify({
        "success": True,
        "filename": unique_name,
    })


if __name__ == "__main__":
    app.run(debug=True, host="0.0.0.0", port=5000)
